### ISSUE TITLE
Jax has no attribute 'linear_util'

### ISSUE THREAD

**Issue by YousufAKhan** [YoshitakaMo/localcolabfold#212]
**Caution: Please only report your issue related to the installation on your local PC or macOS.** If you can get the help message by `colabfold_batch --help` or run a test prediction successfully, your installation is successful. Requests or questions regarding ColabFold features should be directed to [ColabFold repo's issues](https://github.com/sokrypton/ColabFold/issues).

----

**What is your installation issue?**

I am getting the following error when trying to run a basic colabfold_batch command

`2024-02-08 18:12:30,428 Running colabfold 1.5.5 (0cf2621921f2e79a1da9db7ba2ed072291f68e45)

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can 
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2024-02-08 18:12:30,757 Running on GPU
Traceback (most recent call last):
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 2037, in main
    run(
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1292, in run
    from colabfold.alphafold.models import load_models_and_params
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/alphafold/models.py", line 4, in <module>
    import haiku
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/haiku/experimental/__init__.py", line 34, in <module>
    from haiku._src.dot import abstract_to_dot
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/haiku/_src/dot.py", line 163, in <module>
    @jax.linear_util.transformation
  File "/home/yousuf/alphafold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/deprecations.py", line 53, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax' has no attribute 'linear_util'
`

Describe your question here.

Not sure how I can fix this

**Computational environment**

 - OS: Ubuntu 22.04
 - CUDA version if Linux 

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
`

**To Reproduce**

I just ran the vanilla install and got this issue

**My jax version is 0.4.24 and jaxlib is 0.4.24+cuda11.cudnn86 according to python.3.10 -m pip list when I look in the coalbfold-conda/bin

**Comment by brunocuevas** [comment]
I updated the script to install the previous version of jax, and it seems to work.
`"$COLABFOLDDIR/colabfold-conda/bin/pip" install --upgrade "jax[cuda11_pip]==0.4.23" \
    -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

**Comment by YoshitakaMo** [comment]
@brunocuevas Thank you for this issue report! `jax.linear_util` has been moved to `jax.extend.linear_util` since jax 0.4.24. LocalColabFold is affected by this change and should be fixed to the 0.4.23 version.
@YousufAKhan Please download and use the latest `update_linux.sh` to fix this issue.

**Comment by RobinVanSchendel** [comment]
on our HPC we currently have also cuda12 up and running. Does that mean that this fix:

jax[cuda11_pip]==0.4.23

does not work for cuda12?

**Comment by YoshitakaMo** [comment]
> jax[cuda11_pip]==0.4.23 does not work for cuda12?
It worked well with CUDA 12.3 on my Ubuntu environment. But, do you have any problems on your HPC?

**Comment by RobinVanSchendel** [comment]
It turns out I made a mistake; it also works for me!

**Comment by ErikHartman** [comment]
Any fix for this for M1 mac? Tried adding the same things as for in linux update but didn't work. Getting this error:

`RuntimeError: jaxlib version 0.4.24 is newer than and incompatible with jax version 0.4.23. Please update your jax and/or jaxlib packages.`

**Comment by tobias-fritz** [comment]
> Any fix for this for M1 mac? Tried adding the same things as for in linux update but didn't work. Getting this error:
> 
> `RuntimeError: jaxlib version 0.4.24 is newer than and incompatible with jax version 0.4.23. Please update your jax and/or jaxlib packages.`

I ran into the same issue with an Intel mac. For me, downgrading the jaxlib to 0.4.23 (same as jax) fixed the issue.

**Comment by ErikHartman** [comment]
> > Any fix for this for M1 mac? Tried adding the same things as for in linux update but didn't work. Getting this error:
> > `RuntimeError: jaxlib version 0.4.24 is newer than and incompatible with jax version 0.4.23. Please update your jax and/or jaxlib packages.`
> 
> I ran into the same issue with an Intel mac. For me, downgrading the jaxlib to 0.4.23 (same as jax) fixed the issue.

Ok! Did you downgrade both jax and jaxlib? Could you paste some instructions as to what you did? :) Thanks

**Comment by ErikHartman** [comment]
> [cuda11_pip]

Got it. Forgot to downgrade jaxlib as well as jax. Thanks

**Comment by KesharwaniArpita** [comment]
Any idea to solve this issue for colab?

**Comment by csxrzhang** [comment]
> > jax[cuda11_pip]==0.4.23 不适用于 CUDA12？
> 
> 它在我的 Ubuntu 环境中与 CUDA 12.3 配合得很好。但是，您的 HPC 有任何问题吗？

newbility

**Comment by Gabriel-QIN** [comment]
chex 0.1.83 is not compatible with jax-0.4.23.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chex 0.1.87 requires jax>=0.4.27, but you have jax 0.4.23 which is incompatible.
chex 0.1.87 requires jaxlib>=0.4.27, but you have jaxlib 0.4.23 which is incompatible.
Successfully installed jax-0.4.23 jaxlib-0.4.23`

run `pip uninstall chex` works for me.
